[package]
name = "no_complaints_here"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riven = "2.62.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-map = "0.2.3"
